<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>

<a href="/">Home</a>
<a href="/webroot/index.php?route=book/index">Books</a>
<a href="/webroot/index.php?route=index/contact">Contact</a>
|

<?php if (Session::has('user')):?>
    <a href="/webroot/index.php?route=security/logout">Logout</a> (<?=Session::get('user')?>)
<?php else: ?>
    <a href="/webroot/index.php?route=security/login">Login</a>
<?php endif;?>


<hr>
<?=$content?>
<br>
<br>
<br>
<br>
<br>
<hr>
footer &copy;<?=date('Y');?>
</body>
</html>